# -*- coding: utf-8 -*-
"""Copy of assignment_1_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rb9F-wwwaWr7SEiZBeBYa6tUDZv8NrLi
"""

!pip install --upgrade wandb
import wandb
!wandb login 7c2b51b201fca423d3798d6c77c45bc79501464a

"""Download the fashion-MNIST dataset and plot 1 sample image for each class."""

from keras.datasets import fashion_mnist
import wandb
# from wandb.keras import WandbCallback

wandb.init(project='question_4',entity='kumar-vaibhav')
class_names = ['T-shirt/top', 'Trouser/pants', 'Pullover shirt', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag',
			   'Ankle boot']

(trainX, trainy), (testX, testy) = fashion_mnist.load_data()
trainX=trainX / 255.0
testX=testX / 255.0

def log_images():
	set_images=[]
	set_labels=[]
	count=0
	for d in range(len(trainy)):
		if trainy[d]==count:
				set_images.append(trainX[d])
				set_labels.append(class_names[trainy[d]])
				count=count+1
		else:
				pass
		if count==10:
			break
log_images()
wandb.log({"Plot": [wandb.Image(img, caption=caption) for img, caption in zip(set_images, set_labels)]})

!pip install --upgrade wandb
import wandb
!wandb login 7c2b51b201fca423d3798d6c77c45bc79501464a

from wandb.keras import WandbCallback
from keras.datasets import fashion_mnist
from matplotlib import pyplot as plt
(train_X,train_Y),(test_X,test_Y)=fashion_mnist.load_data()

wandb.init(project='question_4',entity='kumar-vaibhav')
class_names=['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']
images=[]
labels=[]
count=0
for i in range(len(train_Y)):
  if train_Y[i]==count:
    images.append(train_X[i])
    labels.append(class_names[train_Y[i]])
    count=count+1
  else:
    pass
  if count==10:
    break
  
wandb.log({"Question 1": [wandb.Image(img, caption=lbl) for img,lbl in zip(images,labels)]})